DECLARE @U5_CODCONT VARCHAR(06) = '';
DECLARE @A1_COD     VARCHAR(12) = ''; 
DECLARE @A1_LOJA    VARCHAR(02) = '';

DELETE AGA990 WHERE AGA_ENTIDA = 'SU5' AND AGA_CODENT = @U5_CODCONT AND AGA_FILIAL = ''
DELETE AGB990 WHERE AGB_ENTIDA = 'SU5' AND AGB_CODENT = @U5_CODCONT AND AGB_FILIAL = ''
DELETE AO4990 WHERE AO4_ENTIDA = 'SU5' AND AO4_CHVREG = @U5_CODCONT AND AO4_FILIAL = ''
DELETE SU5990 WHERE U5_CODCONT = @U5_CODCONT AND U5_FILIAL = ''


DELETE AC8990 WHERE AC8_FILENT = '' AND AC8_ENTIDA = 'SA1' AND AC8_CODENT = @A1_COD + @A1_LOJA AND AC8_CODCON = @U5_CODCONT AND AC8_FILIAL = '' 


