DELETE AGA990 WHERE AGA_ENTIDA = 'SU5' AND AGA_CODIGO IN
( SELECT U5_CODCONT FROM SU5990 WHERE U5_CODCONT IN
( SELECT AC8_CODCON FROM AC8990 WHERE AC8_ENTIDA = 'SA1' AND AC8_CODENT = '@A1_COD' + '@A1_LOJA' ) )

DELETE AGB990 WHERE AGB_ENTIDA = 'SU5' AND AGB_CODIGO IN
( SELECT U5_CODCONT FROM SU5990 WHERE U5_CODCONT IN
( SELECT AC8_CODCON FROM AC8990 WHERE AC8_ENTIDA = 'SA1' AND AC8_CODENT = '@A1_COD' + '@A1_LOJA' ) )

DELETE ZGA990 WHERE ZGA_CODIGO IN
( SELECT AC8_CODCON FROM AC8990 WHERE AC8_ENTIDA = 'SA1' AND AC8_CODENT = '@A1_COD' + '@A1_LOJA' ) )


DELETE SU5990 WHERE U5_CODCONT IN( SELECT AC8_CODCON FROM AC8990 WHERE AC8_ENTIDA = 'SA1' AND AC8_CODENT = '@A1_COD' + '@A1_LOJA' )


DELETE AC8990 WHERE AC8_ENTIDA = 'SA1' AND AC8_CODENT = '@A1_COD' + '@A1_LOJA' 



