/*
DELETE SA1990
DELETE SU5990
DELETE AC8990
DELETE AO4990
DELETE AGB990
*/


SELECT A1_FILIAL, A1_COD, A1_LOJA, A1_NOME, A1_PESSOA, A1_NREDUZ, A1_END, A1_BAIRRO, A1_TIPO, A1_EST, A1_ESTADO, A1_CEP, A1_COD_MUN, A1_MUN, A1_REGIAO, A1_DSCREG, A1_NATUREZ, A1_IBGE, A1_DDI, A1_ENDCOB, A1_DDD, A1_TEL, A1_ENDENT, A1_ENDREC, A1_TRIBFAV, A1_FAX, A1_CONTATO, A1_CGC, A1_PFISICA, A1_INSCR, A1_TELEX, A1_INSCRM, A1_PAIS, A1_VEND, A1_COMIS, A1_CONTA, A1_BCO1, A1_BCO2, A1_BCO3, A1_BCO4, A1_BCO5, A1_TRANSP, A1_TPFRET, A1_COND, A1_DESC, A1_PRIOR, A1_RISCO, A1_LC, A1_VENCLC, A1_CLASSE, A1_LCFIN, A1_MOEDALC, A1_MSALDO, A1_MCOMPRA, A1_METR, A1_PRICOM, A1_ULTCOM, A1_NROCOM, A1_FORMVIS, A1_TEMVIS, A1_ULTVIS, A1_TMPVIS, A1_TMPSTD, A1_CLASVEN, A1_MENSAGE, A1_SALDUP, A1_RECISS, A1_NROPAG, A1_SALPEDL, A1_TRANSF, A1_SUFRAMA, A1_ATR, A1_VACUM, A1_SALPED, A1_TITPROT, A1_DTULTIT, A1_CHQDEVO, A1_DTULCHQ, A1_MATR, A1_MAIDUPL, A1_TABELA, A1_INCISS, A1_SALDUPM, A1_PAGATR, A1_CXPOSTA, A1_ATIVIDA, A1_CARGO1, A1_CARGO2, A1_CARGO3, A1_RTEC, A1_SUPER, A1_ALIQIR, A1_RG, A1_OBSERV, A1_CALCSUF, A1_DTNASC, A1_SALPEDB, A1_CLIFAT, A1_GRPTRIB, A1_BAIRROC, A1_CEPC, A1_MUNC, A1_ESTC, A1_CEPE, A1_BAIRROE, A1_MUNE, A1_ESTE, A1_SATIV1, A1_SATIV2, A1_CODPAIS, A1_CODLOC, A1_TPISSRS, A1_TPESSOA, A1_SATIV3, A1_SATIV4, A1_SATIV5, A1_SATIV6, A1_SATIV7, A1_SATIV8, A1_CODMARC, A1_CODAGE, A1_COMAGE, A1_TIPCLI, A1_EMAIL, A1_DEST_1, A1_DEST_2, A1_CODMUN, A1_DEST_3, A1_HPAGE, A1_CBO, A1_CNAE, A1_CONDPAG, A1_DIASPAG, A1_OBS, A1_AGREG, A1_CODHIST, A1_RECINSS, A1_RECCOFI, A1_RECCSLL, A1_RECPIS, A1_TIPPER, A1_SALFIN, A1_CONTAB, A1_SALFINM, A1_B2B, A1_GRPVEN, A1_CLICNV, A1_INSCRUR, A1_MSBLQL, A1_COMPLEM, A1_HRCAD, A1_DTCAD, A1_CLIPRI, A1_LOJPRI, A1_CODSEG, A1_NUMRA, A1_SITUA, A1_SUBCOD, A1_CDRDES, A1_FILDEB, A1_CODFOR, A1_ABICS, A1_BLEMAIL, A1_TIPOCLI, A1_VINCULO, A1_DTINIV, A1_DTFIMV, A1_LOCCONS, A1_CODMUNE, A1_PERFIL, A1_HRTRANS, A1_UNIDVEN, A1_TIPPRFL, A1_PRF_VLD, A1_PRF_COD, A1_PRF_OBS, A1_REGPB, A1_TPREG, A1_USADDA, A1_SIMPLES, A1_FRETISS, A1_CEINSS, A1_CODSIAF, A1_IDHIST, A1_IRBAX, A1_INDRET, A1_REGESIM, A1_IPWEB, A1_PERCATM, A1_CTARE, A1_RESERVE, A1_MSEXP, A1_ENDNOT, A1_ORIGEM, A1_NIF, A1_ABATIMP, A1_RECIRRF, A1_TIMEKEE, A1_CONTRIB, A1_TDA, A1_FILTRF, A1_INCULT, A1_ENTID, A1_MINIRF, A1_ALIFIXA, A1_CRDMA, A1_PRSTSER, A1_RFABOV, A1_TPDP, A1_PERFECP, A1_RFACS, A1_MATFUN, A1_IENCONT, A1_RECFET, A1_FOMEZER, A1_CODFID, A1_SIMPNAC, A1_ORIGCT, A1_ENTORI, A1_IMGUMOV, A1_RESFAT, A1_IDESTN, A1_NVESTN, A1_ISSRSLC, A1_TPCAMP, A1_CHVCAM, A1_INOVAUT, A1_TPNFSE, A1_OUTRMUN, A1_USERLGA, A1_USERLGI, A1_HREXPO, A1_TPJ, A1_CODTER, A1_CODMEMB, A1_TPMEMB, D_E_L_E_T_, R_E_C_N_O_, R_E_C_D_E_L_, A1_XCD_CDC, A1_XDH_CDC
FROM dbo.SA1990

SELECT U5_FILIAL, U5_CODCONT, U5_CONTAT, U5_CPF, U5_END, U5_BAIRRO, U5_RG, U5_MUN, U5_OAB, U5_EST, U5_CEP, U5_CODPAIS, U5_DDD, U5_FONE, U5_CELULAR, U5_FAX, U5_FCOM1, U5_FCOM2, U5_EMAIL, U5_URL, U5_NIVEL, U5_SEXO, U5_NIVER, U5_RENDA, U5_AUTORIZ, U5_CIVIL, U5_CONJUGE, U5_FILHOS, U5_NOMEF, U5_OPERADO, U5_DIALIG, U5_NDIALIG, U5_HORA1, U5_HORA2, U5_DIAVIS, U5_NDIAVIS, U5_HORAV1, U5_HORAV2, U5_OBS, U5_ATIVO, U5_FUNCAO, U5_GRUPO, U5_DEPTO, U5_STATUS, U5_CLIENTE, U5_LOJA, U5_PROSPEC, U5_ULTCONT, U5_LOJAPRO, U5_PERIOD, U5_TIPO, U5_IDSITE, U5_CODAGA, U5_AGBRES, U5_AGBCEL, U5_AGBFAX, U5_AGBCOM, U5_PAIS, U5_TRATA, U5_IDEXC, U5_CHGKEY, U5_CODSA3, U5_IDESTN, U5_NVESTN, U5_CONPRI, U5_MSBLQL, U5_CODUSR, D_E_L_E_T_, R_E_C_N_O_, R_E_C_D_E_L_, U5_XCOTCOM, U5_XFATPUB, U5_XFINANC, U5_XNF_E, U5_XSRVGRF, U5_XPUBLIC, U5_XBOLELE
FROM dbo.SU5990

SELECT AC8_FILIAL, AC8_FILENT, AC8_ENTIDA, AC8_CODENT, AC8_CODCON, D_E_L_E_T_, R_E_C_N_O_, R_E_C_D_E_L_
FROM dbo.AC8990

SELECT AO4_FILIAL, AO4_ENTIDA, AO4_CHVREG, AO4_CODUSR, AO4_CTRLTT, AO4_PERVIS, AO4_PEREDT, AO4_PEREXC, AO4_PERCOM, AO4_USRCOM, AO4_IDESTN, AO4_NVESTN, AO4_DTVLD, AO4_CODEQP, AO4_PROPRI, AO4_CODUND, AO4_TPACES, AO4_PRIORI, D_E_L_E_T_, R_E_C_N_O_, R_E_C_D_E_L_
FROM dbo.AO4990

SELECT AGB_FILIAL, AGB_CODIGO, AGB_ENTIDA, AGB_CODENT, AGB_TIPO, AGB_PADRAO, AGB_DDI, AGB_DDD, AGB_TELEFO, AGB_COMP, D_E_L_E_T_, R_E_C_N_O_, AGB_XEMAIL, AGB_XTIPO
FROM dbo.AGB990
