--SELECT TOP 1 SNG.NG_CDEPREC FROM SNG990 SNG WHERE SNG.NG_CCONTAB = '1222005'
DECLARE @CONTA VARCHAR(MAX) = '1222005'


SELECT MES_ANO, SUM(ADICAO) ADICAO, SUM(ENTRADAS) ENTRADAS, SUM(SAIDAS) SAIDAS, SUM(BAIXAS) BAIXAS FROM 
(
SELECT
SUBSTRING(CT2.CT2_DATA, 1, 6 ) MES_ANO,
SUM(CT2.CT2_VALOR) ADICAO,
0 ENTRADAS,
0 SAIDAS,
0 BAIXAS
FROM CT2990 CT2
WHERE CT2.D_E_L_E_T_ = ' ' 
AND CT2.CT2_DEBITO = @CONTA 
AND CT2.CT2_LP IN ('001')
GROUP BY
SUBSTRING(CT2.CT2_DATA, 1, 6 )

UNION ALL

SELECT
SUBSTRING(CT2.CT2_DATA, 1, 6 ) MES_ANO,
0 ADICAO,
SUM(CT2.CT2_VALOR)  ENTRADAS,
0 SAIDAS,
0 BAIXAS
FROM CT2990 CT2
WHERE CT2.D_E_L_E_T_ = ' ' 
AND CT2.CT2_DEBITO = @CONTA 
AND CT2.CT2_LP IN ('002')
GROUP BY
SUBSTRING(CT2.CT2_DATA, 1, 6 )

UNION ALL

SELECT
SUBSTRING(CT2.CT2_DATA, 1, 6 ) MES_ANO,
0 ADICAO,
0 ENTRADAS,
SUM(CT2.CT2_VALOR) SAIDAS,
0 BAIXAS
FROM CT2990 CT2
WHERE CT2.D_E_L_E_T_ = ' ' 
AND CT2.CT2_CREDIT = @CONTA 
AND CT2.CT2_LP IN ('002')
GROUP BY
SUBSTRING(CT2.CT2_DATA, 1, 6 )

UNION ALL

SELECT
SUBSTRING(CT2.CT2_DATA, 1, 6 ) MES_ANO,
0 ADICAO,
0 ENTRADAS,
0 SAIDAS,
SUM(CT2.CT2_VALOR) BAIXAS
FROM CT2990 CT2
WHERE
CT2.D_E_L_E_T_ = ' ' AND
CT2.CT2_CREDIT = @CONTA AND 
CT2.CT2_LP IN ('003')
GROUP BY
SUBSTRING(CT2.CT2_DATA, 1, 6 )
) SALDO
GROUP BY MES_ANO