SELECT RD4.RD4_CODIDE,RD4.RD4_CHAVE,RD4.RD4_DESC,SQB.QB_XDTCRIA,SQB.QB_XDTEXTI FROM RD4990 RD4
LEFT JOIN RDK990 RDK ON RD4.RD4_CODIGO = RDK.RDK_CODIGO
LEFT JOIN SQB990 SQB ON RD4.RD4_CODIDE = SQB.QB_DEPTO
WHERE RDK.D_E_L_E_T_ = ' '
AND RD4.D_E_L_E_T_ = ' '
AND SQB.D_E_L_E_T_ = ' '
AND RDK.RDK_STATUS = '1'
AND ( SQB.QB_XDTCRIA <= FORMAT(GETDATE(),'yyyyMMdd') OR SQB.QB_XDTCRIA = '        ' ) 
AND ( SQB.QB_XDTEXTI >= FORMAT(GETDATE(),'yyyyMMdd') OR SQB.QB_XDTEXTI = '        ' ) 